name: build
on: [push]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            -   name: setup go
                uses: actions/setup-go@v3
                with:
                    go-version: 1.18

            -   name: checkout
                uses: actions/checkout@v3

            -   name: test
                run: go test -v ./...
                env:
                    GOFLAGS: "-mod=vendor"

            -   name: run linters
                uses: golangci/golangci-lint-action@v3

    build-docker:
        if: startsWith(github.ref, 'refs/tags/')
        runs-on: ubuntu-latest
        needs: test # Не обязательно, но, если тесты не пройдут, то смысла делать образ нет.
        steps:
            -   name: login to ghcr.io
                uses: docker/login-action@v2
                with:
                    registry: ghcr.io
                    username: ${{ github.actor }}
                    password: ${{ secrets.GITHUB_TOKEN }}

            -   name: prepare docker build
                id: meta
                uses: docker/metadata-action@v4
                with:
                    images: ghcr.io/${{ github.repository }}

            -   name: build and push docker image
                uses: docker/build-push-action@v3
                with:
                    push: true
                    tags: ${{ steps.meta.outputs.tags }}
